// Generated by scripts/i18n_build.mjs. Do not edit by hand.
//
// Part of the generated src/ui/i18n.resolved.generated/ directory: one dense
// locale slice per file (each `: EnTranslations` = typeof en, so tsc red-fails a
// missing or renamed key), a back-compat barrel (index.ts) that re-exports every
// slice and assembles the runtime `translations` map, per-locale lazy loaders
// (loaders.ts), and the pending set (pending.ts). Regenerate with
// `npm run i18n:build` (also wired into `npm run build` and `pretest`).
// Reproducibility is checked by tests/i18n_resolved_equivalence.test.ts.

export const pending: Record<string, readonly string[]> = {
  "es": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "es_ES": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "fr_FR": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "fr_CA": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "en_CA": [],
  "it_IT": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "de_DE": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "zh_CN": [],
  "zh_TW": [],
  "ko_KR": [],
  "ja_JP": [],
  "pt_BR": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "ru_RU": [],
  "cs_CZ": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "nl_NL": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "pl_PL": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "id_ID": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "tr_TR": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "sv_SE": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "vi_VN": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ],
  "da_DK": [
    "hudChrome.warfareShop.buyConfirmBodyGold"
  ]
};
